/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controladora.Encriptar;
import entidades.clavijero;
import entidades.disco;
import entidades.reflector;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Jorge
 */
public class Maquina extends javax.swing.JFrame {

    List<disco> discos;
    Encriptar encriptar;
    String abecedario;
    List<JButton> letras;

    /**
     * Creates new form Maquina
     */
    public Maquina() {
        initComponents();
        abecedario = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        discos = new ArrayList<>();
        discos.add(new disco("Disco 1", "EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q"));
        discos.add(new disco("Disco 2", "AJDKSIRUXBLHWTMCQGZNPYFVOE", "E"));
        discos.add(new disco("Disco 3", "BDFHJLCPRTXVZNYEIWGAKMUSQO", "V"));
        discos.add(new disco("Disco 4", "ESOVPZJAYQUIRHXLNFTGKDCMWB", "J"));
        discos.add(new disco("Disco 5", "VZBRGITYUPSDNHLXAWMJQOFECK", "A"));
        letras = new ArrayList<>();
        letras.add(a);
        letras.add(b);
        letras.add(c);
        letras.add(d);
        letras.add(e);
        letras.add(f);
        letras.add(g);
        letras.add(h);
        letras.add(i);
        letras.add(j);
        letras.add(k);
        letras.add(l);
        letras.add(m);
        letras.add(n);
        letras.add(r);
        letras.add(s);
        letras.add(t);
        letras.add(o);
        letras.add(p);
        letras.add(q);
        letras.add(u);
        letras.add(v);
        letras.add(w);
        letras.add(x);
        letras.add(y);
        letras.add(z);
        ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) jSpinner2.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) jSpinner3.getEditor()).getTextField().setEditable(false);
        salida="";
        clavijero=abecedario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        m = new javax.swing.JButton();
        o = new javax.swing.JButton();
        w = new javax.swing.JButton();
        n = new javax.swing.JButton();
        x = new javax.swing.JButton();
        y = new javax.swing.JButton();
        z = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        a = new javax.swing.JButton();
        s = new javax.swing.JButton();
        b = new javax.swing.JButton();
        t = new javax.swing.JButton();
        c = new javax.swing.JButton();
        v = new javax.swing.JButton();
        d = new javax.swing.JButton();
        u = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        j = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        p3 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.setEditable(false);

        jLabel1.setText("Entrada");

        jLabel2.setText("Salida");

        jButton1.setText("Configurar clavijero");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("MAQUINA ENIGMA");

        jButton3.setText("INICIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        m.setText("M");

        o.setText("O");

        w.setText("W");

        n.setText("N");

        x.setText("X");

        y.setText("Y");

        z.setText("Z");

        p.setText("P");

        q.setText("Q");

        r.setText("R");

        a.setText("A");

        s.setText("S");

        b.setText("B");

        t.setText("T");

        c.setText("C");

        v.setText("V");

        d.setText("D");

        u.setText("U");

        e.setText("E");

        f.setText("F");

        g.setText("G");

        h.setText("H");

        i.setText("I");

        j.setText("J");

        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "R", "S", "T", "O", "P", "Q", "U", "V", "W", "X", "Y", "Z"}));
        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSpinner3.setModel(new javax.swing.SpinnerListModel(new String[] {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "R", "S", "T", "O", "P", "Q", "U", "V", "W", "X", "Y", "Z"}));

        k.setText("K");

        l.setText("L");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Disco 1", "Disco 2", "Disco 3", "Disco 4", "Disco 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setDragEnabled(true);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jList1MouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p3MouseExited(evt);
            }
        });

        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1MouseExited(evt);
            }
        });

        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p2MouseExited(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Arrastrar Disco a Ranuras");

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "R", "S", "T", "O", "P", "Q", "U", "V", "W", "X", "Y", "Z"}));

        jLabel5.setText("Ranura 1");

        jLabel6.setText("Ranura 1");

        jLabel7.setText("Ranura 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(n)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(u)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(w)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(z))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(c)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(d))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(limpiar)
                                    .addGap(38, 38, 38)))
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(e)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f))
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(g)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(h))
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(i)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(k))
                                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(l)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d)
                    .addComponent(e)
                    .addComponent(f)
                    .addComponent(g)
                    .addComponent(h)
                    .addComponent(i)
                    .addComponent(j)
                    .addComponent(k)
                    .addComponent(l)
                    .addComponent(m))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p)
                    .addComponent(q)
                    .addComponent(o)
                    .addComponent(r)
                    .addComponent(s)
                    .addComponent(t)
                    .addComponent(u)
                    .addComponent(v)
                    .addComponent(w)
                    .addComponent(x)
                    .addComponent(y)
                    .addComponent(z)
                    .addComponent(n))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String clavijero;
String salida;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clavijero c = new Clavijero();
        c.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //validaciones
        if (p1.getText().equals("") || p2.getText().equals("") || p3.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debes arrastrar los discos");
            return;
        }
        if (jButton3.getText().equals("INICIAR")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            limpiar.setEnabled(false);
            jButton3.setText("DETENER");
            jList1.setEnabled(false);
            jButton1.setEnabled(false);
        } else {
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            limpiar.setEnabled(true);
            jButton3.setText("INICIAR");
            jButton1.setEnabled(true);
            jList1.setEnabled(true);
            limpiar.doClick();
        }
        //inicio de la maquina
        //insertando discos seleccionados
        encriptar = new Encriptar();
        for (disco d : discos) {
            if (d.getNombre().equals(p1.getText())) {
                d.setPosicionInicial(obtenerPosicion(jSpinner1.getValue().toString()));
                d.setPosicionActual(obtenerPosicion(jSpinner1.getValue().toString()));
                encriptar.setI(d);
            }
            if (d.getNombre().equals(p2.getText())) {
                d.setPosicionInicial(obtenerPosicion(jSpinner2.getValue().toString()));
                d.setPosicionActual(obtenerPosicion(jSpinner2.getValue().toString()));
                encriptar.setII(d);
            }
            if (d.getNombre().equals(p3.getText())) {
                d.setPosicionInicial(obtenerPosicion(jSpinner3.getValue().toString()));
                d.setPosicionActual(obtenerPosicion(jSpinner3.getValue().toString()));
                encriptar.setIII(d);
            }
        }
        //instalando clavijero y reflector
        encriptar.setC(new clavijero(clavijero));
        encriptar.setR(new reflector());


    }//GEN-LAST:event_jButton3ActionPerformed
    private int obtenerPosicion(String letra) {
        for (int i = 0; i < abecedario.length(); i++) {
            if (abecedario.charAt(i) == letra.charAt(0)) {
                return i;
            }
        }
        return 1;
    }

    private Object obtenerLetra(int indice) {
        for (int i = 0; i < abecedario.length(); i++) {
            if (i == indice) {
                return abecedario.charAt(indice) + "";
            }
        }
        return "A";
    }
    private void p1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseExited
        if (p1.getText().equals(p2.getText()) || p1.getText().equals(p3.getText())) {
            p1.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_p1MouseExited

    private void p2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseExited
        if (p2.getText().equals(p1.getText()) || p2.getText().equals(p3.getText())) {
            p2.setText("");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_p2MouseExited

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        p1.setEnabled(false);
        p2.setEnabled(false);
        p3.setEnabled(false);
        p1.setText("");
        p2.setText("");
        p3.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jSpinner1.setValue("A");
        jSpinner2.setValue("A");
        jSpinner3.setValue("A");
        salida="";
        apagarLetras();

// TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    private void jList1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseExited
        if (jList1.isEnabled()) {
            p1.setEnabled(false);
            p2.setEnabled(false);
            p3.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseExited

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
        if (jList1.isEnabled()) {
            if (p1.getText().isEmpty()) {
                p1.setEnabled(true);
            }
            if (p2.getText().isEmpty()) {
                p2.setEnabled(true);
            }
            if (p3.getText().isEmpty()) {
                p3.setEnabled(true);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseEntered

    private void p3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseExited
        if (p3.getText().equals(p1.getText()) || p3.getText().equals(p2.getText())) {
            p3.setText("");
        } // TODO add your handling code here:
    }//GEN-LAST:event_p3MouseExited

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        apagarLetras();
        //movimiento de los discos
        
        if (encriptar.getII().getMuesca().equalsIgnoreCase(jSpinner2.getValue().toString())) {
            if (encriptar.getI().getPosicionActual() == 25) {
                encriptar.getI().setPosicionActual(0);
                jSpinner1.setValue(obtenerLetra(0));
            } else {
                encriptar.getI().setPosicionActual(encriptar.getI().getPosicionActual() + 1);
                jSpinner1.setValue(obtenerLetra(encriptar.getI().getPosicionActual()));
            }
        }
        
        
        if (encriptar.getIII().getMuesca().equalsIgnoreCase(jSpinner3.getValue().toString())) {
            if (encriptar.getII().getPosicionActual() == 25) {
                encriptar.getII().setPosicionActual(0);
                jSpinner2.setValue(obtenerLetra(0));
            } else {
                encriptar.getII().setPosicionActual(encriptar.getII().getPosicionActual() + 1);
                jSpinner2.setValue(obtenerLetra(encriptar.getII().getPosicionActual()));
            }
        }else{
        
        if (encriptar.getII().getMuesca().equalsIgnoreCase(jSpinner2.getValue().toString())) {
            if (encriptar.getII().getPosicionActual() == 25) {
                encriptar.getII().setPosicionActual(0);
                jSpinner2.setValue(obtenerLetra(0));
            } else {
                encriptar.getII().setPosicionActual(encriptar.getII().getPosicionActual() + 1);
                jSpinner2.setValue(obtenerLetra(encriptar.getII().getPosicionActual()));
            }

            if (encriptar.getI().getPosicionActual() == 25) {
                encriptar.getI().setPosicionActual(0);
                jSpinner1.setValue(obtenerLetra(0));
            } else {
                encriptar.getI().setPosicionActual(encriptar.getI().getPosicionActual() + 1);
                jSpinner1.setValue(obtenerLetra(encriptar.getI().getPosicionActual()));
            }
        }
        
        }
        if (encriptar.getIII().getPosicionActual() == 25) {
            encriptar.getIII().setPosicionActual(0);
            jSpinner3.setValue(obtenerLetra(0));
        } else {
            encriptar.getIII().setPosicionActual(encriptar.getIII().getPosicionActual() + 1);
            jSpinner3.setValue(obtenerLetra(encriptar.getIII().getPosicionActual()));
        }
        
        
        

        

        

// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
       //encriptar letra
        char letraEncriptada=encriptar.encriptacion((evt.getKeyChar() + "").toUpperCase());
        iluminarLetra(letraEncriptada+"");
        salida+=letraEncriptada;
        jTextField2.setText(salida); 


    }//GEN-LAST:event_jTextField1KeyReleased
    
    public void iluminarLetra(String letra) {
        for (JButton jb : letras) {
            if (jb.getText().equalsIgnoreCase(letra)) {
                jb.setBackground(Color.YELLOW);
            }
        }
    }

    private void apagarLetras() {
//        try {
//            Thread.sleep(1000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(Maquina.class.getName()).log(Level.SEVERE, null, ex);
//        }
        for (JButton jb : letras) {
            jb.setBackground(new ColorUIResource(238, 238, 238));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables

}
